services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/courses-front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    volumes:
      - ./bot:/app
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
